# Generated by Django 4.2.30 on 2026-08-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0002_alter_share_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='permission',
            field=models.CharField(choices=[('read', 'View details'), ('download', 'Download')], default='read', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='share',
            constraint=models.UniqueConstraint(fields=('file', 'receiver'), name='unique_file_receiver_share'),
        ),
    ]
