# Generated by Django 4.2.30 on 2026-08-14 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0002_alter_folder_id'),
        ('files', '0004_file_deleted_at'),
        ('sharing', '0003_alter_share_permission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='folders.folder'),
        ),
        migrations.AlterField(
            model_name='share',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files.file'),
        ),
        migrations.AddConstraint(
            model_name='share',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('file__isnull', False), ('folder__isnull', True)), models.Q(('file__isnull', True), ('folder__isnull', False)), _connector='OR'), name='share_requires_exactly_one_item'),
        ),
        migrations.AddConstraint(
            model_name='share',
            constraint=models.UniqueConstraint(fields=('folder', 'receiver'), name='unique_folder_receiver_share'),
        ),
    ]
