# Generated by Django 5.2.17 on 2026-08-25 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0007_remove_share_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='permission',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor')], default='viewer', max_length=20),
        ),
    ]
