# Generated by Django 5.2.17 on 2026-08-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_alter_activitylog_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('UPLOAD', 'Upload'), ('DOWNLOAD', 'Download'), ('COPY', 'Copy'), ('CUT', 'Cut'), ('MOVE', 'Move'), ('RENAME', 'Rename'), ('DELETE', 'Move to Trash'), ('RESTORE', 'Restore'), ('PERMANENT_DELETE', 'Permanent delete'), ('CREATE_FOLDER', 'Create folder'), ('ENCRYPT', 'Encrypt'), ('DECRYPT', 'Decrypt'), ('SHARE', 'Share'), ('REVOKE_SHARE', 'Revoke share')], max_length=30),
        ),
    ]
