# Generated by Django 5.2.17 on 2026-08-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0003_alter_folder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
