# Generated by Django 4.2.30 on 2026-08-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_mime_type_alter_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='encryption_nonce',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='encryption_version',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
    ]
